### ISSUE TITLE
[Feat] 報酬計算說明

### ISSUE THREAD

**Issue by johnny890122** [johnny890122/FINDER_react_frontend#101]
老師希望能增加報酬如何計算的[詳細說明](https://muddy-activity-559.notion.site/Tutorial-for-understanding-how-scores-are-calculated-ba94da7f6e434a7196adbaaff22f5361?pvs=4)。

順序上要放在「歡迎！」和「輔助工具」之間。

p.s. 這個應該比較麻煩一點，如果你覺得工作時數有超過之前講好的，想跟老師討論薪資的話。
可以再跟我說，我幫你去講，老師那邊應該不會有太大問題。

**Comment by moneychien19** [comment]
@johnny890122 我在報酬計算頁面新增了範例 1，你幫我看看這樣是不是符合預期，ok 的話我再把其他東西加一加（應該會加在同一個頁面，往下一直疊）

**Comment by moneychien19** [comment]
@johnny890122 我加了範例 2，接下來應該是有個理解測驗，那個我想問會想要讓使用者選擇選項，然後如果選錯的話提示嗎？還是就是讓使用者看過那一頁就好了

**Comment by johnny890122** [comment]
@moneychien19 
可能就做一個選錯 -> 提示有錯 -> 要求再回答 -> 直到正確才可以前往下一頁～
