### ISSUE TITLE
[Feature] 前端生成 session_id 的機制調整

### ISSUE THREAD

**Issue by johnny890122** [johnny890122/FINDER_react_frontend#19]
目前是在 game_start 的地方，由前端生成 session_id，並傳回後端。作為後續辨識的 key。

希望改成 game_start 生成 session_id & player_id。

後續 api 參數 session_id -> player_id。

因為目前是一個 session 只有一個 player，但為了未來程式的彈性，這邊還是改成這樣比較好。

**Comment by moneychien19** [comment]
調整過的版本已寫在 [issue](https://github.com/johnny890122/FINDER_react_frontend/issues/20) 裡
