### ISSUE TITLE
[Feat] Tour-歡迎頁面改成指定使用者要移除的 node，移除後在旁邊加上說明文字

### ISSUE THREAD

**Issue by johnny890122** [johnny890122/FINDER_react_frontend#49]
1. 除了虛擬的 graph，應該要補上原本的911犯罪網絡示意圖
<img width="760" alt="截圖 2024-02-15 上午11 19 24" src="https://github.com/johnny890122/FINDER_react_frontend/assets/54676778/8bbd7c65-ad73-4aa7-be7a-01554925d8d8">
2. 補充示意圖：「怎麼做呢？每一回合，請您在圖中挑選一個點（人物），接著，電腦會移除您所挑選的那個點，以及所有連接到這個點的線。您每一次移除一個點，直到圖中所有的邊被移除為止，就算任務完成。」
範例圖：
<img width="837" alt="截圖 2024-02-15 上午11 19 43" src="https://github.com/johnny890122/FINDER_react_frontend/assets/54676778/f3596b0c-40c2-46aa-8b22-17d9dab1fcf0">
3. 增加以下文字（對應到原本的 page2）
「接下來我們透過一個範例來讓您體會一下遊戲的過程！以下這個網絡圖，展示的是2001年9月11日劫機攻擊美國本土的蓋達組織恐怖份子關係圖。圖中每一個點是一位劫機犯，每一條線顯示他們曾經有通聯紀錄，因此推斷有密謀關係。現在請您開始每次挑選一個點（人物），直到這個恐怖份子的所有關係被移除為止，達成任務。請在以下的網絡圖中，挑選一個點，進行移除。您所選取的節點，會以紅色標示。」

**Comment by johnny890122** [comment]
@moneychien19 這邊說明比較複雜一點，但大致可以對照：https://finder.herokuapp.com/SessionStartLinks/qkgyhjfd 的頁面，應該會很清楚。

**Comment by moneychien19** [comment]
依照口頭討論的結果，還是維持新專案比較互動式的方式，但改成我們指定使用者要移除的 node，移除後在旁邊加上說明文字
