### ISSUE TITLE
[Fix] 報酬頁面顯示

### ISSUE THREAD

**Issue by johnny890122** [johnny890122/FINDER_react_frontend#51]
1. 報酬的顯示，因為要預先顯示都用 FINDER 的 payoff，所以我原本是用目前回合數+n的作法，ex: 第一回合，顯示1-15回合的報酬。
<img width="972" alt="截圖 2024-02-15 上午11 35 08" src="https://github.com/johnny890122/FINDER_react_frontend/assets/54676778/f5e3ec2b-0dc4-4af3-ac1b-c6bd4a40a0e5">
2. line plot 和輔助工具的順序左右調換，比較符合閱讀的順序。
![IMG_115574F427CB-1](https://github.com/johnny890122/FINDER_react_frontend/assets/54676778/6ab073f0-ba05-4f56-a976-ddabc4aa7bf0)
3. 看起來 line plot 的 (x, y) 點和格線沒有對在一起。
<img width="440" alt="截圖 2024-02-15 上午11 38 12" src="https://github.com/johnny890122/FINDER_react_frontend/assets/54676778/86d1cf19-310e-4fa4-8af5-b6a81ed74e81">

**Comment by moneychien19** [comment]
關於 1，口頭討論結果：  

後端回傳的 finder payoff 會是從現在往後十回合，如果按照 AI Finder 會有的報酬，所以這邊先做兩個版本再做比較：
- 顯示過去和未來每個回合的圖
- 只顯示從現在到未來每個回合的圖，過去的就不顯示

**Comment by moneychien19** [comment]
Duplicate Issue https://github.com/johnny890122/FINDER_react_frontend/issues/66，這個 Issue 先關掉
