### ISSUE TITLE
[Feat] Refresh 後網站 Crash

### ISSUE THREAD

**Issue by johnny890122** [johnny890122/FINDER_react_frontend#65]
- [ ] 在正式遊戲畫面，當 refresh 頁面後，網頁會 crash 掉。我猜原因有很多，以後端看到的來說，應該是前端重打了一些 api，但是並未放入正確的 argument，導致無法成功 fetch 新資料。
- [ ] 操作頁面若不小心跳到上一頁再跳回來的話網頁會當機，無法繼續操作（重整也無法），需結束遊戲再重新開始
- [ ] 在 database schema 中，有些欄位是 primary key，必須符合 unique constraint。退回 app 首頁，按刷新頁面，前端生成的 ID 似乎沒有跟著刷新。回到首頁時，需要更新 ID，不然再次打出去的 api，後端資料庫沒辦法順利儲存。

**Comment by moneychien19** [comment]
@johnny890122  
前兩個我修好了，但是第三個是指哪個 id 沒更新
- `playerId` 沒更新應該是預期中的情況
- `gameId` 應該是每次重新進入遊戲都會重新產生一個

這兩條應該沒問題，請再幫我看看是哪邊不符合預期

**Comment by johnny890122** [comment]
@moneychien19 剩下的應該是後端的問題。
