### ISSUE TITLE
[Fix] Payoff chart 顯示

### ISSUE THREAD

**Issue by johnny890122** [johnny890122/FINDER_react_frontend#66]
<img width="757" alt="截圖 2024-03-20 上午10 19 47" src="https://github.com/johnny890122/FINDER_react_frontend/assets/54676778/aa70f55c-e0a8-4329-8a10-8030410fd7ce">

1. human payoff 要用 cumulative sum 顯示，目前看起來是 individual round reward? 
2. y axis 的值最高可以 1 就好，因為根據公式可以得到的最高分是 1。
3. finder payoff 已經接好了，會回傳一個 list（根據我們討論的，是從這個回合開始，都使用 FINDER 的 cumulative sum payoff，前面的回合就不管它），但目前 payoff chart 只有顯示 first round 的 payoff，再麻煩協助 debug。

**Comment by moneychien19** [comment]
1. 有點奇怪，我測試總是選連結程度最高的點，如果用 cumulative sum 的話 human payoff 會超過 1，感覺後端回傳的已經是 cumulative sum 了

**Comment by johnny890122** [comment]
@moneychien19 那感覺是我後端的問題，因為 payoff 目前的設計只有辦法算 individual round payoff。感覺可以前端直接憲改，我後端再來修。

**Comment by moneychien19** [comment]
3. 看起來現在的 payoff api 裡面的 finder payoff 還是只有一個數字而已欸，是後端要重新 deploy 嗎？

**Comment by johnny890122** [comment]
@moneychien19 3. 的問題，我有重新 deploy 了，會回傳從該回合開始都用 finder 的 payoff 了。
不過現在會有一點慢，稍微等一下應該可以回傳成功。
