### ISSUE TITLE
[Feat] 操作網絡介面

### ISSUE THREAD

**Issue by johnny890122** [johnny890122/FINDER_react_frontend#70]
以下是實驗助理測試後的反饋，我覺得你可以斟酌有沒有需要。

- [x] 縮小畫面建議設一個底線不要讓受試者縮到無敵小（這個感覺應該不難）
- [ ] 沒有辦法旋轉（轉移視角）好像有點難以觀看和判斷（這個如果太難感覺就算了）

<img width="744" alt="截圖 2024-03-31 下午7 33 58" src="https://github.com/johnny890122/FINDER_react_frontend/assets/54676778/14b4eb66-732d-4a61-b698-61c64718b203">

**Comment by moneychien19** [comment]
看了一下如果做成 3D 可旋轉的效果的話就不能設定最小的縮放大小了，所以我先設定最小的縮放大小，這個應該比較重要
