### ISSUE TITLE
[Fix] graphData 回傳

### ISSUE THREAD

**Issue by johnny890122** [johnny890122/FINDER_react_frontend#73]
問題：每次回合的 api 都是打完整的 graphData 回來。

推測：前端移除 node 並不是真正移除，而是讓選中的 node 變透明。但是回傳的時候，連變透明的 node 也回傳。

Sol：感覺應該加個 filter，回傳不是透明的 node 即可

**Comment by johnny890122** [comment]
@moneychien19 我抓了新的 code 下來，但後端收到的 graphData 都還是完整的 graph，而非只有畫面上顯示的 node。

**Comment by johnny890122** [comment]
@moneychien19 你講的那邊都正確。我說的「後端收到的 graphData 都還是完整的 graph」，是指即使在好幾個回合後，也就是有一些 node 已被移除，但仍會回傳完整的 5 個 node。

如果這個問題前端要處理太複雜，因為現在資料庫已經用好了，我可以用後端來處理。看你評估的結果

**Comment by moneychien19** [comment]
喔對所以我就是要問是哪一個 api

**Comment by johnny890122** [comment]
這個問題已透過後端處理好。
