### ISSUE TITLE
[Style] 網絡介紹頁面

### ISSUE THREAD

**Issue by johnny890122** [johnny890122/FINDER_react_frontend#97]
<img width="804" alt="截圖 2024-05-10 下午1 36 51" src="https://github.com/johnny890122/FINDER_react_frontend/assets/54676778/fbbd0068-b4e9-4b6d-a60d-f86328af8ad2">

受試者回饋：「目前的設計方式有點像最後點了哪個情境後點開始遊玩就會是那個情境，會誤導使用者？」

Solution: 
1. 可以加一個機制，把介紹網絡的 block 收起來之後，再讓開始遊玩的button 可以按。
2. 把「按下開始遊玩，系統將會隨機挑選一個網絡給您」這段話，加到 button 附近。

**Comment by moneychien19** [comment]
我使用跟 Tour 介紹輔助指標那一頁一樣的機制了，強制看完所有介紹後才能按下一頁
